payload: 
  - DOMAIN-SUFFIX,steamstatic.com
  - DOMAIN-SUFFIX,api.steampowered.com
  
  # - DOMAIN-KEYWORD,google
  # - DOMAIN-KEYWORD,twitch
  # - DOMAIN-KEYWORD,youtube
  # - DOMAIN-KEYWORD,discord
  # - DOMAIN-KEYWORD,telegram
  # - DOMAIN-KEYWORD,gstatic
  # - DOMAIN-KEYWORD,github
  - DOMAIN-SUFFIX,pki.goog
  - DOMAIN-KEYWORD,cloudflare
