name: Manage Release

on:
  push:
    branches:
      - main  # 监控的分支，可以根据实际情况修改

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Set up GitHub CLI authentication
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete old release and tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Actions 自动生成的令牌
        run: |
          REPO="${{ github.repository }}"

          # 删除旧的名为 'release' 的 release
          if gh release view release --repo $REPO &>/dev/null; then
            echo "删除之前创建的 release ===> 'release'"
            gh release delete release -y --repo $REPO || echo "Failed to delete release 'release'"
          else
            echo "No release named 'release' found"
          fi

          # 删除本地标签
          if git show-ref --tags | grep -q 'refs/tags/release'; then
            echo "删除本地 tag ===> 'release'"
            git tag -d release || echo "Failed to delete local tag 'release'"
          else
            echo "No local tag named 'release' found"
          fi

          # 删除远程标签
          if git ls-remote --tags origin | grep -q 'refs/tags/release'; then
            echo "删除远程 tag ===> 'release'"
            git push origin :refs/tags/release || echo "Failed to delete remote tag 'release'"
          else
            echo "No remote tag named 'release' found"
          fi

      - name: Create new tag
        run: |
          echo "创建新的tag ===> release'"
          git tag release
          git push origin release

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Actions 自动生成的令牌
        run: |
          REPO="${{ github.repository }}"
          echo "Creating new release"
          gh release create release --title "release" --notes "Automated release for tag 'release'" --repo $REPO
